services:
  aasx-server:
    container_name: aasx-server
    hostname: aasx-server
    build:
      context: ./../..
      dockerfile: ./src/docker/Dockerfile-AasxServerBlazor
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./aasxs:/usr/share/aasxs
    command: --start-index 0 --no-security --edit --data-path /usr/share/aasxs --external-blazor http://localhost:5001