services:
  aasx-server:
    container_name: aasx-server
    hostname: aasx-server
    build:
      context: ./../..
      dockerfile: ./src/docker/Dockerfile-AasxServerBlazor
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - C:\GitClones\aasx-server\content-for-demo\aasxs:/usr/share/aasxs
    command: --start-index 0 --no-security --aasx-in-memory 1000 --data-path "./aasxs" --edit --external-blazor http://localhost:5001 --with-mongodb "mongodb://mongo:mongo@localhost:27017/"
